export const ADD_PEOPLE = 'ADD_PEOPLE';
export const ADD_LEVEL = 'ADD_LEVEL';
export const ADD_SELECTED = 'ADD_SELECTED';
export const ADD_SELECTED_VISIBLE_PEOPLE = 'ADD_SELECTED_VISIBLE_PEOPLE';
export const ADD_OPENED_LAST_NODES_LEVEL = 'ADD_OPENED_LAST_NODES_LEVEL';
export const ADD_LEVEL_WIDTH = 'ADD_LEVEL_WIDTH';
